In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import string


billboard_df = pd.read_csv("C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Mining\\Week 4\\Week 4 Exercise\\billboard_lyrics_1964_2015.csv", encoding='latin-1')
with open('C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Mining\\Week 4\\Week 4 Exercise\\PositiveWords.txt', 'r') as file:
    positiveWords = file.read().replace('\n', ' ')
with open('C:\\Users\\Gabe\\Documents\\Bellevue University\\Data Mining\\Week 4\\Week 4 Exercise\\NegativeWords.txt', 'r') as file:
    negativeWords = file.read().replace('\n', ' ')

billboard_df['Lyrics'] = billboard_df['Lyrics'].astype(str)
print(billboard_df.head(1))
print(billboard_df.tail(1))

   Rank         Song                         Artist  Year  \
0     1  wooly bully  sam the sham and the pharaohs  1965   

                                              Lyrics  Source  
0  sam the sham miscellaneous wooly bully wooly b...     3.0  
      Rank                   Song                       Artist  Year  \
5099   100  how deep is your love  calvin harris and disciples  2015   

                                                 Lyrics  Source  
5099   i want you to breathe me in let me be your ai...     1.0  


In [4]:
corpus = billboard_df['Lyrics']
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())


vectorized words

['0120', '02', '03', '04', '07', '082', '10', '100', '1000', '100000', '100k', '100s', '1010', '102', '104', '105', '106', '109', '10s', '10slooking', '10th', '11', '110', '111123oclock', '112', '112we', '1130', '12', '120', '1205', '123', '1230', '1234', '125', '129', '12move', '12string', '12yearold', '13', '13th', '14', '146', '14th', '15', '15000', '151', '15s', '15th', '16', '16s', '16th', '17', '1780', '17th', '18', '1800430', '183', '185', '18s', '18th', '19', '1900mixalot', '1910', '1949', '1951', '1955', '1959', '1963', '1965', '196667', '1968', '1969', '1970', '1972', '1973', '1975', '1979', '1980', '1981', '1982', '1982and', '1984', '1985', '1989', '1991', '1992', '1994', '1999', '1breaking', '1chorus', '1i', '1if', '1oh', '1repeat', '1rollercoaster', '1st', '1when', '1you', '20', '200', '2000', '2001', '2002', '2003', '2004', '2004girl', '2004its', '2006', '2007', '2008', '2009', '2010', '2011', '2013', '2014', '2015', '2015written', '2016', '2016s', '203

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
df = pd.DataFrame({'text' : corpus})
#check for positive words and negative words

positive_list = list(positiveWords.split(" "))
negative_list = list(negativeWords.split(" "))

for word in positive_list:
    df['positive'] = df.text.str.count(word)

for w in negative_list:
    df['negative'] = df.text.str.count(w)

df['TotScore'] = df.positive - df.negative

print("")
print(df)

Z = sum(df['TotScore'])
print("")
print("Positive - Positive Value : Negative - Negative Value")
print("")
print("Overall Score:  ",Z)


                                                   text  positive  negative  \
0     sam the sham miscellaneous wooly bully wooly b...         0         0   
1      sugar pie honey bunch you know that i love yo...         0         0   
2                                                               0         0   
3      when i woke up this morning you were on my mi...         0         0   
4      you never close your eyes anymore when i kiss...         0         0   
...                                                 ...       ...       ...   
5095  enrique iglesias dime si es verdad me dijeron ...         0         0   
5096                                                nan         0         0   
5097   going out tonight changes into something red ...         0         0   
5098   oh man oh man oh man not againyeah i learned ...         0         0   
5099   i want you to breathe me in let me be your ai...         0         0   

      TotScore  
0            0  
1            0  

In [7]:
# Extra Credit - Relates to Ch. 5-7

# Jaccard Distance on Two Different Songs

import collections

def intersection(s1, s2) :   
    intersect = s1 & s2 ; 
    return intersect;  
    
def jaccard_index(s1, s2) :  
    size_s1 = len(s1);  
    size_s2 = len(s2);  
    intersect = intersection(s1, s2);   
    size_in = len(intersect);  
    jaccard_in = size_in  / (size_s1 + size_s2 - size_in);  
    return jaccard_in;  
  
def jaccard_distance(jaccardIndex)  : 
    jaccard_dist = 1 - jaccardIndex;   
    return jaccard_dist; 

list_of_lyrics = billboard_df['Lyrics'].to_list()

# I Can't Help Myself - Four Tops
first_song = billboard_df['Lyrics'].iloc[1]
first_song_lyric_list = list(first_song.split(" "))

# How Deep Is Your Love - Calvin Harris
last_song = billboard_df['Lyrics'].iloc[-1]
last_song_lyric_list = list(last_song.split(" "))

first_song_words = set(first_song_lyric_list)
last_song_words = set(last_song_lyric_list)

jaccardIndex_Songs = jaccard_index(first_song_words, last_song_words)

print("Jaccard 1965 Song & 2015 Song Distance = ",jaccard_distance(jaccardIndex_Songs)*100, "%")


Jaccard 1965 Song & 2015 Song Distance =  84.45945945945947 %
